### ISSUE TITLE
Внести коррективы в соответствии с пожеланиями заказчика

### ISSUE THREAD

**Issue by YedrenBaton** [PI21b-group-dynamics/recipe-book#8]

**Comment by SpacCloud** [comment]
А что не понравилось заказчику? Всё же хорошо было

**Comment by YedrenBaton** [comment]
> А что не понравилось заказчику? Всё же хорошо было

Нужно было включить раздел справки в пользовательское меню и добавить окно авторизации пользователя, чтобы он мог получать доступ к своим рецептам с разных устройств

**Comment by Scorpi-ON** [comment]
Ничего, главное, что существенно переделывать ничего не понадобилось :)
